// ============================================================
// DC HOSA Help Ticket System — Google Apps Script
// Install in: Extensions > Apps Script (from the Ticket Tracker sheet)
//
// HOW IT WORKS:
//   1. Officer submits Form 1 → ticket appears in Ticket Tracker
//      + all three state staff receive an email notification
//   2. State staff open the Ticket Tracker sheet directly to:
//      - Set "Assigned To" (claim the ticket)
//      - Update "Status" as work progresses
//      - Add "Response Notes" when resolved
//   No second form needed.
// ============================================================

// ── CONFIGURATION ────────────────────────────────────────────
const CONFIG = {
  // State staff emails — update before deploying
  STAFF_EMAILS: [
    "hosadistrictofcolumbia@gmail.com",   // State Advisor (Shreyas)
    "officeradvisor@dchosa.org",           // Officer Advisor  — update
    "officercoach@dchosa.org"              // Officer Coach    — update
  ],

  // Sheet names (must match exactly)
  TICKET_SHEET:  "Form Responses 1",  // Officer submission form responses
  TRACKER_SHEET: "Ticket Tracker",    // The master tracker tab

  // Tracker column positions (1-indexed)
  COL_TICKET_ID:       1,   // A — auto-generated by script
  COL_TIMESTAMP:       2,   // B — from form
  COL_OFFICER:         3,   // C — from form
  COL_CATEGORY:        4,   // D — from form
  COL_AREA:            5,   // E — from form
  COL_TITLE:           6,   // F — from form
  COL_DESCRIPTION:     7,   // G — from form
  COL_URGENCY:         8,   // H — from form
  COL_NOTES:           9,   // I — from form
  COL_STATUS:          10,  // J — staff edits directly in sheet
  COL_ASSIGNED_TO:     11,  // K — staff edits directly in sheet
  COL_RESPONSE_NOTES:  12,  // L — staff edits directly in sheet

  // Link to the Ticket Tracker sheet — paste your URL here
  TRACKER_URL: "https://docs.google.com/spreadsheets/d/YOUR_SHEET_ID"
};

// ── TICKET SUBMISSION TRIGGER ─────────────────────────────────
// Set this as the ONLY trigger needed.
// Extensions > Apps Script > Triggers > Add Trigger:
//   Function:     onTicketSubmit
//   Event source: From spreadsheet
//   Event type:   On form submit

function onTicketSubmit(e) {
  const ss      = SpreadsheetApp.getActiveSpreadsheet();
  const sheet   = ss.getSheetByName(CONFIG.TICKET_SHEET);
  const tracker = ss.getSheetByName(CONFIG.TRACKER_SHEET);

  const row    = e.range.getRow();
  const values = sheet.getRange(row, 1, 1, 9).getValues()[0];

  const ticketId = generateTicketId(tracker);
  const [timestamp, officer, category, area, title, description, urgency, notes] = values;

  // Write to Ticket Tracker
  tracker.appendRow([
    ticketId,
    timestamp,
    officer,
    category,
    area,
    title,
    description,
    urgency,
    notes,
    "Open",  // default status
    "",      // assigned to — staff fills this in
    ""       // response notes — staff fills this in
  ]);

  applyStatusFormatting(tracker);

  // Notify all state staff
  sendNewTicketEmail(ticketId, officer, category, area, title, description, urgency, notes, timestamp);
}


// ── EMAIL: NEW TICKET NOTIFICATION ───────────────────────────
function sendNewTicketEmail(ticketId, officer, category, area, title, description, urgency, notes, timestamp) {
  const urgencyLabel  = urgency || "Not specified";
  const isUrgent      = urgencyLabel.toLowerCase().includes("high") || urgencyLabel.toLowerCase().includes("today");
  const subjectPrefix = isUrgent ? "[URGENT] " : "";

  const subject = subjectPrefix + "[DC HOSA Ticket " + ticketId + "] " + title;

  const body = `
A new help ticket has been submitted by a DC HOSA State Officer.

────────────────────────────────
TICKET ${ticketId}
────────────────────────────────
Officer:    ${officer}
Category:   ${category}
Area:       ${area}
Urgency:    ${urgencyLabel}
Submitted:  ${Utilities.formatDate(new Date(timestamp), Session.getScriptTimeZone(), "MMM d, yyyy h:mm a")}

TITLE:
${title}

DESCRIPTION:
${description}

${notes ? "ADDITIONAL NOTES:\n" + notes + "\n" : ""}
────────────────────────────────

To handle this ticket, open the Ticket Tracker and:
  1. Set "Assigned To" to your name
  2. Change "Status" to In Progress
  3. Contact the officer directly to help
  4. Update "Status" to Resolved and add a note in "Response Notes" when done

Ticket Tracker: ${CONFIG.TRACKER_URL}

– DC HOSA Ticket System
  `.trim();

  CONFIG.STAFF_EMAILS.forEach(email => {
    MailApp.sendEmail({ to: email, subject: subject, body: body });
  });
}


// ── HELPERS ───────────────────────────────────────────────────

// Generate sequential ticket ID: #001, #002, etc.
function generateTicketId(tracker) {
  const lastRow = tracker.getLastRow();
  if (lastRow <= 1) return "#001";
  const lastId = tracker.getRange(lastRow, 1).getValue().toString();
  const num    = parseInt(lastId.replace("#", "")) || 0;
  return "#" + String(num + 1).padStart(3, "0");
}

// Color-code the Status column whenever a ticket is added
function applyStatusFormatting(tracker) {
  const data = tracker.getDataRange().getValues();
  for (let i = 1; i < data.length; i++) {
    const status = data[i][CONFIG.COL_STATUS - 1];
    const cell   = tracker.getRange(i + 1, CONFIG.COL_STATUS);
    if      (status === "Open")              { cell.setBackground("#FFF3E0"); cell.setFontColor("#854F0B"); }
    else if (status === "In Progress")       { cell.setBackground("#E3F2FD"); cell.setFontColor("#185FA5"); }
    else if (status === "Resolved")          { cell.setBackground("#E8F5E9"); cell.setFontColor("#3B6D11"); }
    else if (status === "Needs Escalation")  { cell.setBackground("#FFEBEE"); cell.setFontColor("#A32D2D"); }
  }
}


// ── SETUP HELPER (run once manually) ─────────────────────────
// In Apps Script, select setupTrackerSheet from the function dropdown
// and click Run. Do this once after creating the spreadsheet.

function setupTrackerSheet() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();

  let tracker = ss.getSheetByName(CONFIG.TRACKER_SHEET);
  if (!tracker) tracker = ss.insertSheet(CONFIG.TRACKER_SHEET);

  // Headers
  const headers = [
    "Ticket ID", "Submitted", "Officer", "Category", "Area",
    "Title", "Description", "Urgency", "Notes",
    "Status", "Assigned To", "Response Notes"
  ];
  tracker.getRange(1, 1, 1, headers.length).setValues([headers]);

  // Header row styling
  tracker.getRange(1, 1, 1, headers.length)
    .setBackground("#1A237E")
    .setFontColor("#FFFFFF")
    .setFontWeight("bold");

  tracker.setFrozenRows(1);

  // Column widths
  tracker.setColumnWidth(1,  80);   // Ticket ID
  tracker.setColumnWidth(2,  120);  // Submitted
  tracker.setColumnWidth(3,  160);  // Officer
  tracker.setColumnWidth(4,  130);  // Category
  tracker.setColumnWidth(5,  160);  // Area
  tracker.setColumnWidth(6,  220);  // Title
  tracker.setColumnWidth(7,  280);  // Description
  tracker.setColumnWidth(8,  120);  // Urgency
  tracker.setColumnWidth(9,  200);  // Notes
  tracker.setColumnWidth(10, 120);  // Status
  tracker.setColumnWidth(11, 140);  // Assigned To
  tracker.setColumnWidth(12, 300);  // Response Notes

  // Dropdown: Status (col J)
  tracker.getRange(2, CONFIG.COL_STATUS, 500).setDataValidation(
    SpreadsheetApp.newDataValidation()
      .requireValueInList(["Open", "In Progress", "Resolved", "Needs Escalation"], true)
      .build()
  );

  // Dropdown: Assigned To (col K)
  tracker.getRange(2, CONFIG.COL_ASSIGNED_TO, 500).setDataValidation(
    SpreadsheetApp.newDataValidation()
      .requireValueInList(["Shreyas", "Officer Advisor", "Officer Coach"], true)
      .build()
  );

  Logger.log("Ticket Tracker setup complete.");
}
